openapi: 3.0.0
info:
  title: Webex Admin Address Book Archive Users API
  version: 1.0.0
  description: The Webex Admin APIs provide comprehensive programmatic access to administrative functions for managing Webex organizations, users, licenses, and settings. These APIs enable automation of user provisioning, license assignment, compliance management, and audit event retrieval. Administrators can integrate with enterprise identity systems, enforce security policies, monitor usage, and streamline onboarding/offboarding processes. The APIs support granular control over organizational resources, making them ideal for large-scale deployments and custom admin tooling.
tags:
- name: Archive Users
paths:
  /identity/organizations/{orgId}/v1/ArchivedUser/{useruuid}:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArchiveUser'
              example:
                schemas:
                - urn:scim:schemas:core:1.0
                - urn:scim:schemas:extension:cisco:commonidentity:1.0
                userName: test_user2@example.com
                emails:
                - primary: true
                  type: work
                  value: test_user2@example.com
                name:
                  givenName: Mike
                  familyName: Tang
                organization: 410139c6-3bff-4404-9782-09a456ba2cae
                id: b96936c9-5b86-4a01-8969-e945c91b62f6
                meta:
                  created: '2019-01-25T00:53:13.000Z'
                  lastModified: '2019-01-25T00:53:13.000Z'
                  location: https://webexapis.com/identity/scim/410139c6-3bff-4404-9782-09a456ba2cae/v1/UserArchives/b96936c9-5b86-4a01-8969-e945c91b62f6
                  deleted: '2019-01-25T00:53:13.001Z'
                displayName: Mike Tang
        '400':
          description: 'Bad Request: The request was invalid or cannot be processed. An accompanying error message explains the issue.'
        '401':
          description: 'Unauthorized: Authentication credentials were missing or invalid.'
        '403':
          description: 'Forbidden: The request was understood but access is denied.'
        '404':
          description: 'Not Found: The requested URI is invalid, or the resource (such as a user) does not exist. Also returned when the requested format is not supported for the method.'
        '405':
          description: 'Method Not Allowed: The request was made using an unsupported HTTP method.'
        '409':
          description: 'Conflict: The request could not be processed because it conflicts with an existing system rule. For example, a person may not be added to a room more than once.'
        '410':
          description: 'Gone: The requested resource is no longer available.'
        '415':
          description: 'Unsupported Media Type: The request was made without specifying a media type or used a media type that is not supported.'
        '423':
          description: 'Locked: The requested resource is temporarily unavailable. A Retry-After header may indicate how many seconds to wait before retrying.'
        '428':
          description: 'Precondition Required: File(s) cannot be scanned for malware and must be force-downloaded.'
        '429':
          description: 'Too Many Requests: Too many requests have been sent in a given time and the request has been rate limited. A Retry-After header indicates how many seconds to wait before retrying.'
        '500':
          description: 'Internal Server Error: Something went wrong on the server. If the issue persists, feel free to contact the [Webex Developer Support team](/explore/support).'
        '502':
          description: 'Bad Gateway: The server received an invalid response from an upstream server. Try again later.'
        '503':
          description: 'Service Unavailable: The server is overloaded with requests. Try again later.'
        '504':
          description: 'Gateway Timeout: An upstream server failed to respond on time. If your query uses max parameter, please try to reduce it.'
      summary: Get Archive User
      operationId: getArchiveUser
      description: 'The `useruuid` is the unique identifier of a user in the system. It is assigned when the user is created and can be retrieved through **GET Users** API.<br/>


        **Authorization**


        OAuth token issued by the Identity Broker.


        One of the following OAuth scopes is required:


        - `identity:people_rw`.

        - `identity:people_read`.


        The following administrators can use this API:


        - `Account in the specified organization with one of the following roles: id_full_admin, id_user_admin, id_readonly_admin`.

        - `Proxy account managing the specified organization with one of the following roles: id_full_admin, id_user_admin, id_readonly_admin`.


        <br/>'
      tags:
      - Archive Users
      parameters:
      - name: orgId
        in: path
        description: The unique identifier for the organization.
        required: true
        example: 410139c6-3bff-4404-9782-09a456ba2cae
        schema:
          type: string
      - name: useruuid
        in: path
        description: The unique identifier for the user.
        required: true
        example: b96936c9-5b86-4a01-8969-e945c91b62f6
        schema:
          type: string
components:
  schemas:
    MetaObject:
      type: object
      description: Response metadata.
      required:
      - created
      - lastModified
      - version
      - location
      properties:
        resourceType:
          type: string
          example: User
        organizationID:
          type: string
          example: The organization ID of the user
        created:
          type: string
          example: '2023-01-11T17:38:31.605Z'
          description: The date and time the group was created.
        lastModified:
          type: string
          example: '2023-01-11T17:38:31.605Z'
          description: The date and time the group was last changed.
        version:
          type: string
          example: '"W\/\"e180ee84f0671b1\""'
          description: The version of the user.
        location:
          type: string
          example: https://webexapi.com/identity/scim/0ae87ade-8c8a-4952-af08-318798958d0c/v2/Users/3426a8e3-d414-4bf0-a493-4f6787632a13
          description: The resource itself.
    ArchiveUser:
      type: object
      required:
      - schemas
      - id
      - userName
      - emails
      - meta
      properties:
        schemas:
          type: array
          items:
            type: string
            example: urn:scim:schemas:core:1.0,urn:scim:schemas:extension:cisco:commonidentity:1.0
          description: An array of schema URNs that define the structure of the SCIM resource.
        userName:
          type: string
          example: test_user2@example.com
          description: The unique identifier for the user. This must be set to the user's primary email address. The `userName` value must be unique across Webex and is used for authentication.
        emails:
          type: array
          items:
            $ref: '#/components/schemas/EmailObject'
          description: A list of the user's email addresses.
        name:
          $ref: '#/components/schemas/NameObject'
        organization:
          type: string
          example: 410139c6-3bff-4404-9782-09a456ba2cae
          description: The unique identifier for the organization.
        id:
          type: string
          example: b96936c9-5b86-4a01-8969-e945c91b62f6
          description: The unique identifier for the user.
        displayName:
          type: string
          example: Mike Tang
          description: The display name of the user in Webex.
        meta:
          $ref: '#/components/schemas/MetaObject'
    EmailObject:
      type: object
      properties:
        value:
          type: string
          example: user1@example.home.com
          description: The email address.
        type:
          type: string
          enum:
          - work
          - home
          - room
          - other
          description: The type of the email.
        display:
          type: string
          example: home email description
          description: A human-readable description, primarily used for display purposes.
        primary:
          type: boolean
          description: Email status boolean value. If the type is work and primary is true, the value must equal `userName`.
    NameObject:
      type: object
      description: The components of the user's real name.
      properties:
        givenName:
          type: string
          example: Sarah
          description: The given name of the user, or first name in most Western languages (e.g., "Sarah" given the full name "Ms. Sarah J Henderson, III").
        familyName:
          type: string
          example: Henderson
          description: The family name of the user, or last name in most Western languages (e.g., "Henderson" given the full name "Ms. Sarah J Henderson, III").
        middleName:
          type: string
          example: Jane
          description: The middle name(s) of the user (e.g., "Jane" given the full name "Ms. Sarah J Henderson, III").
        honorificPrefix:
          type: string
          example: Mr.
          description: The honorific prefix(es) of the user, or title in most Western languages (e.g., "Ms." given the full name "Ms. Sarah J Henderson, III").
        honorificSuffix:
          type: string
          example: III
          description: The honorific suffix(es) of the user, or suffix in most Western languages (e.g., "III" given the full name "Ms. Sarah J Henderson, III").
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: /
          scopes: {}
          tokenUrl: /
      type: oauth2
    bearer-key:
      type: http
      description: e.g. Bearer YOUR_AUTHORIZATION_TOKEN
      scheme: bearer
      bearerFormat: JWT
    bearerAuth:
      type: oauth2
      description: OAuth 2.0 Bearer token authentication
      flows:
        authorizationCode:
          authorizationUrl: https://webexapis.com/v1/authorize
          tokenUrl: https://webexapis.com/v1/access_token
          scopes:
            spark:applications_token: Create access tokens for Service Apps
